io:
  data_folder: data
  image_folder: imgs
  csv_file: car_imgs_4000.csv
  training_folder: trainings
  training_name: deeper_cnn_normed_CEloss
params:
  iterations: 10
  #size has to be divisible by 2**4 non squarable sizes are padded
  image_resize: 256
  seed: 0
  device: cuda
